### ISSUE TITLE
Api Version 2017–01–17

### ISSUE THREAD

**Issue by JordanDalton** [oldtimeguitarguy/mechanical-turk#1]
Is Mechanical Turk API version 2017-01-17 a roadmap item for this package?

**Comment by karlhepler** [comment]
I didn't even know about that until just now, researching your comment. That must have just come out, because I was last working with Mechanical Turk last month. All I can say is that it's about time they came to their senses and introduced a json rest api.

I probably will update this for that version... not sure when though... but probably within the next few months.
